# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Landing Page
email: quinn.t.coyle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Example description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://quinncoyle.com" # the base hostname & protocol for your site
instagram_username: jekyllrb
github_username:  qcoyle

# Build settings
markdown: kramdown

theme: jekyll-theme-dinky